try{
  let a;
  console.log(a.length)
}catch(err){
  console.log("err")
}